version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: development

    command: gradle bootRun
    depends_on:
      - db
    ports:
      - "8080:8080"

    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASS=postgres

    volumes:
      - .:/workspace
      - gradle-data-volume:/home/gradle/.gradle

  postgres:
    image: "postgres:lastest"
    ports:
      - "5432:5432"

    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb

volumes:
  gradle-data-volume:
  postgres-data-volume:
